exclude: 'docs|node_modules|migrations|.git|.tox'
default_language_version:
  python: python3.8
fail_fast: true
default_stages: [commit, push]

repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
      - id: trailing-whitespace
        files: (^|/).+\.(py|html|sh|css|js)$
        args:
          - --markdown-linebreak-ext=md
      
      - id: bandit
        name: bandit
        description: 'Bandit is a tool for finding common security issues in Python code'
        entry: bandit
        language: python
        types: [python]
      
      - id: flake8
        args:
          - --max-line-length=120
          - --ignore=E731
          - --exclude=backend/*/*/migrations/*
  
  - repo: git://github.com/Lucas-C/pre-commit-hooks.git
      sha: v1.0.1
      hooks:
      -   id: remove-crlf
      -   id: remove-tabs
  
  - repo: git://github.com/trbs/pre-commit-hooks-trbs.git
      sha: e233916fb2b4b9019b4a3cc0497994c7926fe36b
      hooks:
      -   id: forbid-executables
          exclude: manage.py|setup.py
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
      sha: v1.1.0
      hooks:
      -   id: python-safety-dependencies-check
  - repo: https://github.com/ambv/black
      rev: stable
      hooks:
        - id: black
          language_version: python3.8