version: "3.6"

services:
  db:
    image: "postgres:12.4"
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
      - ./containers_data/db/postgres/backups:/backups:z
      - ./containers_data/db/postgres/logs:/var/log/postgresql:z
    env_file: backend/.env
    networks:
      - backend

  broker:
    image: "rabbitmq:alpine"
    networks:
      - backend

  result:
    image: "redis:alpine"
    networks:
      - backend

  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    image: django-biolerplate-backend
    tty: true
    ports:
      - 8001:8001
      - 3000:3000
    volumes:
      - ./backend:/home/app/web/backend/
    env_file: backend/.env
    depends_on:
      - db
      - broker
      - result
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
    driver: local
