version: "3.6"

services:
  db:
    image: "postgres:alpine"
    volumes:
      - .db:/var/lib/postgresql/data

  broker:
    image: "rabbitmq:alpine"

  result:
    image: "redis:alpine"
  
  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    image: django-biolerplate-backend
    stdin_open: false
    tty: true
    # command: sh entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/user/app/
    env_file: backend/.env
    depends_on:
      - db
      - broker
      - result
