release: python3 manage.py migrate --settings=onlineBenevolent.settings.production
web: gunicorn -k uvicorn.workers.UvicornWorker onlineBenevolent.asgi:application --bind 0.0.0.0:$PORT --log-level debug
# worker: REMAP_SIGTERM=SIGQUIT celery -A onlineBenevolent.celery worker -B --loglevel=info --without-mingle --without-gossip --without-heartbeat
# celery_beat: python manage.py --settings=onlineBenevolent.settings.production celery beat --loglevel=info
