release: python3 manage.py migrate --settings=onlineBenevolent.settings.production
web: gunicorn -k uvicorn.workers.UvicornWorker onlineBenevolent.asgi:application --bind 0.0.0.0:$PORT --log-level debug
