# Generated by Django 3.1 on 2020-08-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_auto_20200822_1204'),
        ('users', '0003_auto_20200822_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meta.area', verbose_name='Area in Charge'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text=''),
        ),
    ]
