# Generated by Django 3.1 on 2020-08-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_auto_20200822_1204'),
        ('users', '0005_auto_20200822_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='area_in_charge',
        ),
        migrations.AddField(
            model_name='user',
            name='areas_in_charge',
            field=models.ManyToManyField(related_name='envoy_areas_in_charge', to='meta.Area', verbose_name='Area in Charge'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text=''),
        ),
    ]
