# Generated by Django 3.1 on 2020-08-22 12:04

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='order the field in the app')),
            ],
            options={
                'verbose_name': 'CaseType',
                'verbose_name_plural': 'CaseTypes',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.RenameModel(
            old_name='Place',
            new_name='Area',
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Area', 'verbose_name_plural': 'Area'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Problem', 'verbose_name_plural': 'Problems'},
        ),
        migrations.AlterModelOptions(
            name='projectclass',
            options={'ordering': ('name',), 'verbose_name': 'ProjectClass', 'verbose_name_plural': 'ProjectClasses'},
        ),
    ]
