# Generated by Django 3.1 on 2020-09-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_auto_20200822_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectclass',
            name='type',
            field=models.CharField(choices=[('Yearly', 'Seasonal - Occur  each Year.'), ('Monthly-Hijri', 'Monthly - repeated at each Hijri Monthly'), ('Monthly', 'Monthly - repeated Monthly'), ('Daily', 'Daily - repeated Daily')], default='Daily', max_length=128, verbose_name='Status'),
        ),
    ]
