# Generated by Django 3.1 on 2020-09-26 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200912_1626'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='case',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='projects.case', verbose_name='Case'),
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='patch',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='delivery.patch', verbose_name='Patch'),
        ),
        migrations.AlterIndexTogether(
            name='confirmation',
            index_together={('case', 'patch')},
        ),
    ]
